### ISSUE TITLE
Websocket demo

### ISSUE THREAD

**Issue by tomstandly** [BingX-API/BingX-swap-api-doc#6]
What is demo function for using websocket?

**Comment by binbincai410** [comment]
Hi, you can refer to the following code
```
#coding: utf-8

import zlib
import gzip
import io

from websocket import create_connection

def gzip_str(string_: str) -> bytes:
    return gzip.compress(string_.encode())


def gunzip_bytes_obj(bytes_obj: bytes) -> str:
    return gzip.decompress(bytes_obj).decode()

def main():
  print ("connect")
  ws = create_connection("wss://open-ws-swap.bingbon.pro/ws")
  print ("before sub")
  ws.send('{ "id": "id1", "reqType": "sub", "dataType": "market.trade.detail.BTC-USDT"}')
  print ("after sub")
  while True:
      print ("Receiving...")
      result =  ws.recv()
      print ("Received '%s'", gunzip_bytes_obj(result))
  ws.close()

if __name__ == "__main__":
  main()
```

**Comment by tomstandly** [comment]
Thanks for your reply. function do not show anything and shows this errors:
connect
Traceback (most recent call last):
  File "<module1>", line 29, in <module>
  File "<module1>", line 18, in main
  File "\Python\Python38-32\lib\site-packages\websocket\_core.py", line 601, in create_connection
    websock.connect(url, **options)
  File "\Python\Python38-32\lib\site-packages\websocket\_core.py", line 248, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
  File "\Python\Python38-32\lib\site-packages\websocket\_handshake.py", line 57, in handshake
    status, resp = _get_resp_headers(sock)
  File "\Python\Python38-32\lib\site-packages\websocket\_handshake.py", line 148, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 403 Forbidden

**Comment by ThisisAqib** [comment]
@binbincai410  Hi, do you know how to use the above code with API to get the account order updates?
